global:
  scrape_interval: 5s  # Scrape metrics every 5 seconds

scrape_configs:
  - job_name: 'node-app'
    static_configs:
      - targets: ['node-app:7575']  # Target the Node.js service in Docker
